#!/bin/sh

if [ `id -u` -ne 0 ]; then
	echo "This command must be executed by root."
	exit 1
fi

# Use DESTDIR and PREFIX if no QSU_* alternatives where found
[ ! -z "${DESTDIR}" ] && [ -z "${QSU_DESTDIR}" ] && QSU_DESTDIR="${DESTDIR}"
[ ! -z "${PREFIX}" ]  && [ -z "${QSU_PREFIX}"]   && QSU_PREFIX="${PREFIX}"

# Defaults
[ -z "${QSU_DESTDIR}" ] && QSU_DESTDIR=""
[ -z "${QSU_PREFIX}" ]  && QSU_PREFIX="/usr/local"

echo "Installing in '${QSU_DESTDIR}${QSU_PREFIX}'."

mkdir -p ${QSU_DESTDIR}${QSU_PREFIX}

install -o root -m 4711 build/qsu ${QSU_DESTDIR}${QSU_PREFIX}/bin/qsu

mkdir -p ${QSU_DESTDIR}${QSU_PREFIX}/var/db/qsu
chmod 700 ${QSU_DESTDIR}${QSU_PREFIX}/var/db/qsu
